### 유저 등록
POST http://localhost:8020/api/users/localUsers
Content-Type: application/json

{
  "userName": "김민경",
  "mobileNumber": "01010101010",
  "email": "김민경@example.com",
  "birth": "2000-01-01",
  "gender": "FEMALE",
  "userStatus": "ACTIVE",
  "tier": "STANDARD",
  "roleName": "USER",
  "loginId": "김민경",
  "password": "김민경"
}

### 유저 상태 업데이트
PUT http://localhost:8020/api/users/1/status
Content-Type: application/json

{
  "status": "INACTIVE"
}

### 유저 등급 업데이트
PUT http://localhost:8020/api/users/1/grade
Content-Type: application/json

{
  "tier": "ROYAL"
}
