### 유저 등록
POST http://localhost:8020/api/users/localUsers
Content-Type: application/json

{
  "userName": "John Doe",
  "mobileNumber": "01051278121",
  "email": "johndoe@example.com",
  "birth": "1995-03-09",
  "gender": "MALE",
  "userStatus": "ACTIVE",
  "tier": "STANDARD",
  "roleName": "USER",
  "loginId": "test",
  "password": "test"
}

### 유저 상태 업데이트
PUT http://localhost:8020/api/users/1/status
Content-Type: application/json

{
  "status": "INACTIVE"
}

### 유저 등급 업데이트
PUT http://localhost:8020/api/users/1/grade
Content-Type: application/json

{
  "tier": "ROYAL"
}
