# eureka 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    non-secure-port: ${server.port}
    instance-id: API-SERVER-${server.port}
