# eureka 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    healthcheck:
      enabled: true
#    registry-fetch-interval-seconds: 3
  instance:
    appname: API-SERVER
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5

