spring:
  application:
    name: api-server
  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
        show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
    active: dev  # 배포시 prod로 변경
    # 마지막에 실행되는 파일이 앞의 설정을 덮어쓰기 때문에 사용에 주의가 필요
    group:
      prod:
        eureka, jpa, dbcp2, actuator
      dev:
        jpa, dbcp2
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB


# 서버 포트 설정
server:
  port: 8010
  shutdown: graceful

eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'

secure-key-manager:
  password: simsimbook
  url: https://api-keymanager.nhncloudservice.com
  path: /keymanager/v1.0/appkey/{appkey}/secrets/{keyid}
  appKey: qTQNj7LyHhdAazH3

object-storage:
  auth-url: b9d98b2722e34ea09a48babd26dedb8a
  password: 413f34b377e14d2b857c1441dab08606
  storage-url: 6253409e99ad4847814ae3e2d30306ea
  tenant-id: ebe2292c911d4f8aa4cfeda67ef067d9
  username: 32c6d1c4cef44e2789f387f9391962ac

database:
  username: 97f78245ad8446ce9267b29b075f80a7
  password: f2880bd868cd445c9f1c16e13b977f04

redis:
  host: 7098f39a110b4eb88c68ffd65f18774f
  port: 6379
  password: d183598bca794d998bada10b352f57ad

elasticsearch:
  data: 1bf3dfed48184557a8eec43f70d82de7

rabbitmq:
  data: 7bcf9993624c4ccf9140a44e40608808