### simsimhe-books에서 json으로 뽑아낸 데이터 저장 (일괄 저장)
POST localhost:8010/api/shop/elastic/document/save
Content-Type: application/json


### simsimhe-books에 데이터 저장
POST localhost:8010/api/shop/elastic/document
Content-Type: application/json

{
  "id": 10000,
  "title": "테스트1000",
  "description": "테스트1000 설명입니다",
  "author": "테스트 작가",
  "bookImage": "https",
  "tags": [
    "국내도서",
    "소설"
  ],
  "publishedAt": "2025-01-19",
  "salePrice": 19000
}




### document 수정
POST localhost:8010/elastic/document/06Oh3pMBUDE5eABL4uCm
Content-Type:application/json

{
  "title": "한강"
}



### simsimhe-books 인덱스에서 한강과 연관있는 데이터 검색
GET localhost:8010/api/shop/elastic/document?keyword=한강



### 인덱스에 있는 데이터 부분 삭제
DELETE localhost:8010/api/shop/elastic/document/2




