### POST issueCoupons - 유저들에게 쿠폰 발급(전체)
POST http://localhost:8010/api/admin/coupons/issue
Content-Type: application/json

{
  "userIds": [1,2,5,6],
  "couponTypeId": 19
}

### POST issueCoupons - 유저들에게 쿠폰 발급(책)
POST http://localhost:8010/api/admin/coupons/issue
Content-Type: application/json

{
  "userIds": [1,2,5,6],
  "couponTypeId": 20
}

### POST issueCoupons - 유저들에게 쿠폰 발급(카테고리)
POST http://localhost:8010/api/admin/coupons/issue
Content-Type: application/json

{
  "userIds": [1,2,5,6],
  "couponTypeId": 24
}

### GET getCoupon - 특정 쿠폰 하나 가져오기
GET http://localhost:8010/api/shop/coupons/125

### GET getUnusedCouponByCouponType - 유저가 가진 특정 쿠폰 타입 쿠폰 중 미사용 쿠폰을 가져온다.
GET http://localhost:8010/api/shop/users/1/coupons/unused?couponTypeId=2

### GET getCoupons - 유저가 가진 쿠폰들을 가져온다
GET http://localhost:8010/api/shop/users/1/coupons

### GET getUnusedCoupons - 유저의 쿠폰 중 미사용된 쿠폰을 가져온다.
GET http://localhost:8010/api/shop/users/1/coupons/unused

### GET getEligibleCouponsToBook - 유저의 쿠폰 중 적용가능한 쿠폰 만 가져온다.
GET http://localhost:8010/api/shop/users/11/coupons/unused?bookId=3

### POST expiredCoupon - 유저의 쿠폰을 만료시킨다.
POST http://localhost:8010/api/admin/users/1/coupons/exprired?couponId=1

### DELETE deleteCoupon - 유저의 쿠폰을 삭제한다.
DELETE http://localhost:8010/api/shop/users/1/coupons/1

### GET calDiscountAmount - 쿠폰의 할인액을 계산한다.
GET http://localhost:8010/api/shop/coupons/13/calculate?bookId=3&quantity=2

### GET getUnusedCoupons
GET http://localhost:8010/api/shop/users/91/coupons/unused

### GET getUserCouponDiscount
GET http://localhost:8010/api/shop/users/91/coupon-discounts