### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### POST couponType 생성 - 책
POST http://localhost:8020/api/admin/couponTypes
Content-Type: application/json

{
  "couponTypeName": "책 쿠폰",
  "period": 30.0,
  "deadline": null,
  "stacking": false,
  "couponPolicyId": 5,
  "couponTargetType": "책",
  "targetId": 1
}

### POST couponType 생성 - 카테고리
POST http://localhost:8020/api/admin/couponTypes
Content-Type: application/json

{
  "couponTypeName": "카테고리 쿠폰",
  "period": null,
  "deadline": "2025-06-29T00:00:00",
  "stacking": false,
  "couponPolicyId": 4,
  "couponTargetType": "카테고리",
  "targetId": 1
}

### POST couponType 생성 - 전체
POST http://localhost:8020/api/admin/couponTypes
Content-Type: application/json

{
  "couponTypeName": "전체 쿠폰",
  "period": 180,
  "deadline": null,
  "stacking": false,
  "couponPolicyId": 4,
  "couponTargetType": "전체",
  "targetId": null
}

### POST couponType 생성 - Valid 위반
POST http://localhost:8020/api/admin/couponTypes
Content-Type: application/json

{
  "couponTypeName": "Valid 위반",
  "period": null,
  "deadline": "2025-06-29T00:00:00",
  "stacking": false,
  "couponPolicyId": 5,
  "couponTargetType": "전체",
  "targetId": 2
}

### GET getAllCouponType - 모든 쿠폰 타입 가져오기
GET http://localhost:8020/api/admin/couponTypes

### GET getCouponType - 쿠폰 타입을 하나 가져온다.
GET http://localhost:8020/api/admin/couponTypes/1

### GET getCouponTypeByPolicyId - 특정 쿠폰 정책과 연결된 쿠폰 타입들을 가져온다.
GET http://localhost:8020/api/admin/couponTypes?couponPolicyId=4

### DELETE 쿠폰 타입 삭제
DELETE http://localhost:8020/api/admin/couponTypes/2